### ISSUE TITLE
IndexError: index 1 is out of bounds for dimension 1 with size 1

### ISSUE THREAD

**Issue by balabanahei** [ChenJoya/2dtan#5]
The error is :

Traceback (most recent call last):
  File "/home/yu/.jupyter/ngsv/2dtan/train_net.py", line 161, in <module>
    main()
  File "/home/yu/.jupyter/ngsv/2dtan/train_net.py", line 155, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "/home/yu/.jupyter/ngsv/2dtan/train_net.py", line 75, in train
    arguments,
  File "/home/yu/.jupyter/ngsv/2dtan/tan/engine/trainer.py", line 113, in do_train
    device=cfg.MODEL.DEVICE,
  File "/home/yu/.jupyter/ngsv/2dtan/tan/engine/inference.py", line 94, in inference
    return evaluate(dataset=dataset, predictions=predictions, nms_thresh=nms_thresh)
  File "/home/yu/.jupyter/ngsv/2dtan/tan/data/datasets/evaluation.py", line 45, in evaluate
    candidates, scores = score2d_to_moments_scores(score2d, num_clips, duration)
  File "/home/yu/.jupyter/ngsv/2dtan/tan/data/datasets/utils.py", line 20, in score2d_to_moments_scores
    scores = score2d[grids[:,0], grids[:,1]]
IndexError: index 1 is out of bounds for dimension 1 with size 1

How can I fix it? I use torch==1.3.1 and cuda==10.2. What's your version? Thanks!

**Comment by ycWang9725** [comment]
Hi, I got same error on torch1.1, and on torch1.5 it disappeared. 
Hope to help:)

**Comment by DW-Lay** [comment]
the dimension error   sometimes it's due to the "squeeze()_"  operation  cause unexpected 
result ,you can check it in your code carefully

**Comment by wjn922** [comment]
I have the same problem.
In some cases, the dim of prediction would become 1d instead of 2d.
How to solve this problem?

**Comment by DW-Lay** [comment]
I eliminated a certain dimension in the process of squeeze(). I suggest you carefully check whether there are any related problems during the related operation. You should judge this

**Comment by Zzz512** [comment]
Hello,i meet the same problem when i train Tacos and i solved it by reset batchsize to 33 or other numbers.It may be generated because tacos training datasets count to 4001 and when batchsize are [16,32,64,etc.] the last batch always have only 1 sample,iterator then get an unnomal tensor with lacking of one dimension.
